x-cloud-env: &cloud-env
 CLOUD_URL: "http://34.203.14.74:5000"  # adapt IP/port

services: 
 edge1:
   build:
     context: .
     dockerfile: docker/Dockerfile.edge
   image: edge
   ports:
     - "5001:5001"
   environment:
     <<: *cloud-env
     UVICORN_PORT: 5001
     
 edge2:
   build:
     context: .
     dockerfile: docker/Dockerfile.edge
   image: edge
   ports:
     - "5002:5002"
   environment:
     <<: *cloud-env 
     UVICORN_PORT: 5002