FROM python:3-slim

WORKDIR /app

# all dependencies before copying -> this layer has to be changed less freq.
COPY docker/dependencies/requirements_iot.txt . 
RUN pip install -r requirements_iot.txt


COPY src/iot.py . 
COPY src/utils.py .
COPY camera_set ./camera_set


CMD ["python", "-u", "iot.py"]