FROM python:3-slim

WORKDIR /app
RUN apt-get update && apt-get install -y curl

# install dependencies before copying -> this layer has to be changed less freq.
COPY docker/dependencies/requirements_cloud.txt . 
RUN pip install -r requirements_cloud.txt

COPY src/cloud.py . 
COPY res/credentials/creds.yaml res/credentials/creds.yaml
COPY src/config.py .

COPY



CMD ["python", "-u", "cloud.py"]