FROM python:3-slim

WORKDIR /app

#all dependencies before copying -> this layer has to be changed less freq.
COPY docker/dependencies/requirements_alarm.txt . 
RUN pip install -r requirements_alarm.txt

RUN mkdir -p /app/logs

COPY src/config.py . 
COPY src/alarm.py . 
COPY src/logger.py .


CMD ["python", "-u", "alarm.py"]